version: 0.2
env:
  variables:
    S3_BUCKET: "jerdevventrasfrontend"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build: 
    commands:
      - echo Installing source NPM dependencies...
      - cd front-admin
      - rm -rf node_modules
      - rm -rf package-lock.json
      - rm -rf dist
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
  post_build:
    commands:
      - aws s3 cp ./dist/front-admin s3://$S3_BUCKET --recursive --acl public-read --cache-control "max-age=86400"
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: '*'
  discard-paths: yes
